import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jakarta.variable} antialiased`}
      >
              <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="relative min-h-screen bg-background selection:bg-primary/30 selection:text-foreground">
              {/* global decorative gradient blobs */}
              <div className="pointer-events-none fixed -top-48 -left-48 w-[800px] h-[800px] bg-primary/20 blur-[150px] rounded-full z-0" />
              <div className="pointer-events-none fixed -bottom-48 -right-48 w-[800px] h-[800px] bg-purple-500/10 blur-[150px] rounded-full z-0" />
              
              <div className="relative z-10">
                {children}
              </div>
            </div>
          </ThemeProvider>

      </body>
    </html>
  );
}
